### ISSUE TITLE
doi for this repo?

### ISSUE THREAD

**Issue by cvanvelt** [AllenInstitute/scrattch.mapping#45]
Would it be possible to create a DOI for this repo to make it easier to cite when links are not allowed?

**Comment by UCDNJJ** [comment]
Hi Cindy, I just created a new release and associated a DOI with Zenodo.  Here's the DOI: 10.5281/zenodo.10939013 (https://doi.org/10.5281/zenodo.10939013)

![image](https://github.com/AllenInstitute/scrattch.mapping/assets/6441552/4f76a70b-2113-442f-a0d7-24ed03feb634)
